"""add deletion status column for category

Revision ID: 78702d858fc4
Revises: eb8ade3e1ab2
Create Date: 2026-08-20 20:59:44.818308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78702d858fc4'
down_revision = 'eb8ade3e1ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
