"""add role to users

Revision ID: eb8ade3e1ab2
Revises: 
Create Date: 2026-08-15 13:12:19.332174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8ade3e1ab2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_status_check'), type_='check')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_price_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('products_stock_check'), type_='check')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), server_default='user', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('products_stock_check'), 'stock >= 0')
        batch_op.create_check_constraint(batch_op.f('products_price_check'), 'price >= 0::numeric')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('orders_status_check'), "status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'delivering'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])")

    # ### end Alembic commands ###
